### ISSUE TITLE
Newsletters / Lewsnetter

### ISSUE THREAD

**Issue by joubertredrat** [n1trux/awesome-sysadmin#10]
E-mail marketing application (create and send e-mail newsletter via SES). Includes subscription management, delivery, bounce and complaint notification, templates, and some stats.

https://github.com/bborn/lewsnetter

**Comment by n1trux** [comment]
There are a lot of TODOs in this app's README, maybe we should resolve them first?

**Comment by n1trux** [comment]
close because of #51
