### ISSUE TITLE
add Visitors to Analytics

### ISSUE THREAD

**Issue by nodiscc** [n1trux/awesome-sysadmin#114]
similar to GoAccess

http://www.hping.org/visitors/
demo output: http://www.hping.org/visitors/report.html
usage: http://www.hping.org/visitors/doc.html

package available in Debian repositories

**Comment by n1trux** [comment]
This project seems to be dead because the time stamp is from 2006.

Do you use it?

**Comment by nodiscc** [comment]
I mostly used GoAccess, though Visitors has a nice feature: it can also generate visual path analysis graphs using Graphviz (GoAccess does not allow this). I used it once.

Overall the 2 projects are essentially the same thing, and GoAccess is maintained. Feel free to close this issue.

**Comment by n1trux** [comment]
kk, GoAccess it is then :) thanks for your insight!
