### ISSUE TITLE
License from kahun/awesome-sysadmin

### ISSUE THREAD

**Issue by garethsaxby** [n1trux/awesome-sysadmin#130]
The original source of this fork, [kahun/awesome-sysadmin](https://github.com/kahun/awesome-sysadmin), has no license against it, so is covered under standard copyright, whilst this fork has the CC-BY-SA license applied in [this commit](https://github.com/n1trux/awesome-sysadmin/commit/3abf5b4f63dcd7b6ea7ec572bf27239d80621496#diff-61e0bdf7e1b43c5c93d9488b22e04170).

I believe the fork occurred [at this commit](https://github.com/kahun/awesome-sysadmin/commit/48fe9bc5245fd5fc66149ba072376c41548c891b) with the [tree at this time](https://github.com/kahun/awesome-sysadmin/tree/48fe9bc5245fd5fc66149ba072376c41548c891b) not containing a license.

Was permission obtained from the original maintainer? I know that the original project is in a very infrequently updated state, however with no license on the original content, if there's no permission then it seems that there's no right to apply a license to this repo?

Sorry if this has been discussed before; I've had a search through the issues and couldn't see any mention of the license against the repository itself.

**Comment by n1trux** [comment]
>Was permission obtained from the original maintainer?

I tried and failed to contact him multiple times, but I doubt that this doesn't fall under Fair Use or that he has anything against it. It's just a list.

>if there's no permission then it seems that there's no right to apply a license to this repo?

I asked that myself and then concluded that the facts that @kahun accepted contributions and allowed forks before as well as his name in the "forked from kahun/awesome-sysadmin" below the repository name would be enough for now.

If you can contact him somehow, I'd really appreciate it.

**Comment by n1trux** [comment]
License of @kahun's repo is now CC-BY-SA, which should be covered by mentioning him at the top of the repository. If @kahun likes, I'll add a file with all the contributors in them.
