### ISSUE TITLE
Threat Intelligence Free Solution - Karma

### ISSUE THREAD

**Issue by portantier** [n1trux/awesome-sysadmin#132]
Hi,

You can add Karma to your list.

Karma is a free web solution that can be used to add the organization assets (domains, websites, networks, etc), and Karma periodically search this assets on various Threat Intelligence Feeds and reports if any of this assets is listed. 

Also, Karma alerts on bad configurations, like DNS open zone transfers, bad SSL configurations and more.

Link: https://karma.securetia.com

Regards!

**Comment by dopefish** [comment]
Are you sure this is open-source?

**Comment by mipapo** [comment]
Think this is the repo for that or? https://github.com/usc-isi-i2/Web-

**Comment by chauffer** [comment]
It does not seem to be opensource.

@mipapo - that seems to be another project

**Comment by n1trux** [comment]
License unclear, no link on the original site to a FOSS repo and this should still be a PR. Feel free to resolve these issues and submit a PR for it.
