### ISSUE TITLE
digitalocean/netbox

### ISSUE THREAD

**Issue by ad-m** [n1trux/awesome-sysadmin#190]
Hello,

There is a [digitalocean/netbox](https://github.com/digitalocean/netbox). I am not sure this software meets the guidelines. I don't know them very good (It is not part of the scope of my responsibility), but it might pass. The code is clean. Created by a responsible company and corresponds to similar programs listed in the collection.

Greetings,

**Comment by n1trux** [comment]
cool, can you do a PR?
