### ISSUE TITLE
Should Sentry be on the list?

### ISSUE THREAD

**Issue by ardichoke** [n1trux/awesome-sysadmin#196]
Looking through the monitoring section, I see that you have Sentry listed. I would question if they actually belong on the awesome-sysadmin list though. While /most/ of their code is open source, it is not all open source. It also doesn't seem to be released under an open source license (or at least I couldn't find a mention of them releasing under an open source license on their site). The free version is also strictly limited in use. I'd say their model is closer to Splunk's model than to an open source model.

**Comment by n1trux** [comment]
Yes, you're right. It's copyrighted. Please do a PR :)
