### ISSUE TITLE
UptimeRobot

### ISSUE THREAD

**Issue by Martin-Pitt** [n1trux/awesome-sysadmin#205]
Heard a good review of this one running for years: https://uptimerobot.com/
> nigeljohnwade [12:51 PM] 
> I have been using it for years, it appears to do what it says on the tin reliably

**Comment by ardichoke** [comment]
Correct me if I'm wrong, but it looks like that is released under a proprietary, non open source license which makes it "not awesome"

**Comment by n1trux** [comment]
Yes, it's Copyrighted. A good alternative would be Monit, which is already on our list in the [Monitoring](../../awesome-sysadmin#monitoring) section.
