### ISSUE TITLE
Add mailin

### ISSUE THREAD

**Issue by ad-m** [n1trux/awesome-sysadmin#223]
It's free, simple, useful and has free online version. See https://github.com/Flolagale/maili .

**Comment by ardichoke** [comment]
I assume you're actually referring to [mailin](https://github.com/Flolagale/mailin), not maili (which doesn't seem to be a thing)...

I think this doesn't belong on awesome-sysadmin so much as it does on one of the awesome development lists, as it is a tool for ingesting email into a web app.

**Comment by ad-m** [comment]
Yes, I made a typo in the project name. From my perspective, mailin is an effective tool for verifying email server settings like http://mail-tester.com/or http://isnotspam.com/.

**Comment by n1trux** [comment]
>I think this doesn't belong on awesome-sysadmin so much as it does on one of the awesome development lists, as it is a tool for ingesting email into a web app.

Indeed. Closed.
