### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [n1trux/awesome-sysadmin#25]
We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

**Comment by n1trux** [comment]
There's [bayandin/awesome-awesomeness](https://github.com/bayandin/awesome-awesomeness), which I forked into [n1trux/awesome-awesomeness](https://github.com/n1trux/awesome-awesomeness). Please consider adding your repositories there, too :)

In my opinion, everybody is free to fork my repo, but it stays where it is. You could fork the awesome-... repos into yours and create pull requests, maybe there will be a flow both up- and downstream this way.

**Comment by jeffreyjackson** [comment]
cc @dkhamsing what do you think?

**Comment by dkhamsing** [comment]
Hm fork and keep it up to date..? I dunno

**Comment by nbhatti** [comment]
Most of the forks are not going to be up2date. A very few people will find time to pull and update their forks. So, I guess a pull request would eventually help grow the list.

-- 
Muhammad Naseer Bhatti
Sent with Airmail
