### ISSUE TITLE
backup gem!

### ISSUE THREAD

**Issue by stevenolen** [n1trux/awesome-sysadmin#4]
Your backup list should definitely include this backup gem (ruby):
http://meskyanichi.github.io/backup/v4/

It's a really awesome tool for those with ruby installed!

**Comment by n1trux** [comment]
How does this Gem scale? Did you try it with lots of files or is it more suited for Ruby projects?

When you come up with a nice description or even a PR I'll be happy to add it.

**Comment by n1trux** [comment]
closing because lack of feedback.
