### ISSUE TITLE
Another backup tool to consider

### ISSUE THREAD

**Issue by derekp7** [n1trux/awesome-sysadmin#5]
Was wondering if you would like to evaluate a backup tool I wrote, called Snebu?  Documentation is at www.snebu.com, and is hosted on Github.  In short, it is a snapshot style backup (same style as rsnapshot and similar), but it has global multi-client deduplication, files are stored as lzo-compressed files in the target location, and metadata is in an SQLite database (although this data can be exported to a flat file too, for additional recovery / safety options).  Benefits are a fairly open storage format (you can manually recover any file without using the tool if needed), compression, global multi-client file level deduplication, and if using a separate backup server you can install it in a restricted user account (no root needed).  And you can run it from the server without installing any software in the clients (it just needs ssh access, along with [gnu] find and tar).  What's missing: currently no encryption support (should have this shortly, via a compressing/encrypting tar filter called tarccrypt, that I'm working on), and it doesn't do block-level dedup (so not really suitable for backing up KVM image files, although I'm also working on integrating with a client-side utility that will generate the "find" and "tar" output directly from the VM image files).

I would really like to get some more eyeballs on this, before I start recommending it to others.  I've been dogfooding it myself for a while, with about 30 - 40 RHEL [3 - 6] VMs I'm backing up.

**Comment by n1trux** [comment]
Seems nice, I think I will definitely evaluate it for home usage.

Do you think it works in a corporate setting to back up macs?

When you add a short description (50-100 characters) and maybe additionally create a pull request, I'd be glad to add it to the list.

**Comment by derekp7** [comment]
Any setting that is good with rsnapshot should work out with snebu.  If you need plugins for specific applications (such as databases, etc), the client script does have a nice plugin feature (to execute pre/post scripts)  I've already got one for Oracle, but need to document the plugin architecture.  Also, for backing up Macs, you will need to adjust the parameters in the `tar` command in the client script (take out the --selinux, --acls, and --xattrs flags if your Mac tar doesn't support them, and possibly replace them with other extended flags that it does support).

For scalability, I've used it for the past couple years to back up about 40 Linux hosts, keeping 14 daily, 6 weekly, and 12 monthly backups (approx 1200 backupsets total).  Most of the recent work has been in improving response times of the various sqlite calls.  A future project will be adding the option to use a full-featured DB behind it, such as mysql, postgresql, or even oracle.

Anyway, if you run into any issues, drop me a line on the project site, or email me directly.  Thanks.

**Comment by n1trux** [comment]
can you push out a PKGBUILD and/or Arch Linux package? That'd be very nice for testing purposes, I think the people in the Arch forums would love a thread about this.

**Comment by derekp7** [comment]
I've already did one a while ago, at https://aur.archlinux.org/packages/snebu however thanks for reminding me, I need to update it with the latest version.  I also have an srpm, which builds on Fedora and RHEL 6/7.  If I get a couple more people to try it out and report success, I'll submit the package to Fedora, and then work on Debian.

**Comment by n1trux** [comment]
If you updated your PKGBUILD, please comment again :)

Thanks for your effort!

**Comment by derekp7** [comment]
I've rebuilt the package, and uploaded the current version to AUR.  Haven't ran through its paces on Arch yet -- I guess its time for me to automate the validation testing, and have it auto-test against multiple distributions.
