### ISSUE TITLE
propose: split control panels

### ISSUE THREAD

**Issue by joubertredrat** [n1trux/awesome-sysadmin#67]
Hi @n1trux,

I'm looking here that Control Panels will be big with mine new insertions, then, I think is good idea to split into suboptions, Control Panels will continue, but will have "hosting panel", "email panel", "DNS panel" as example.

with the new format would be:
Control Panels
* Web hosting
[...]
* E-mail
[...]
* DNS
[...]
* Revision Control
[...]
* Virtualization
[...]
* Others
[...]

Talk to me that you think

**Comment by n1trux** [comment]
Good idea, do it. Close this with a future commit by inserting "closes #67" ;)

**Comment by joubertredrat** [comment]
Fixed
