### ISSUE TITLE
Mailserver / Modoboa

### ISSUE THREAD

**Issue by joubertredrat** [n1trux/awesome-sysadmin#7]
Mail hosting made simple 
https://github.com/tonioo/modoboa/

**Comment by n1trux** [comment]
well, since the build is failing, there are no screenshots and the project seems to be another hip new thing, why should we use it in production?

**Comment by joubertredrat** [comment]
I use in production.

http://modoboa.org/en/

**Comment by n1trux** [comment]
okay, please create a PR with a (meaningful!) description.

Thank you.
