### ISSUE TITLE
new Organization for awesome lists

### ISSUE THREAD

**Issue by joubertredrat** [n1trux/awesome-sysadmin#81]
I'm looking here that have a lot of lists around github, but they are scattered.

Then why not propose a new Organization for all lists? Administration continues with each other as is now, however, the organization will provide visibility for all lists.

So it will be easy for a list group to help each other list group.

@n1trux @sindresorhus @Kickball @ziadoz @sorrycc @aleksandar-todorovic 

...
wow, have a lot of people to quote!

===
[edited out mass CC due to lack of relevance for this discussion -- n1trux]

**Comment by sindresorhus** [comment]
I don't really see the benefit tbh. Discovery is already solved by my `awesome` list. From experience people have more incentive to make good lists when have the feeling of ownership.

**Comment by joubertredrat** [comment]
@avelino @benoitjadinon @busterc @drobakowski @dypsilon @fffaraz @hachiojipm @h4cc @isRuslan @jondot @JStumpp @kdabir @kozross @krispo @kud1ing @lauris @LewisJEllis @markets @matteocrippa @passy @qinwf @razum2um @sindresorhus @sorrycc @svaksha @vinta @yissachar @weblancaster @zhaopuming

**Comment by joubertredrat** [comment]
@akullpp @rizo @seancoyne @rabbiabram @quozd @ziadoz @Fr0sT-Brutal @mat0thew @ahkscript @bolshchikov @addyosmani @davidsonfellipe @lvwzhen @addyosmani @enaqx @mateusortiz @Granze @gianarb @instanceofpro @diegocard @HugoGiraudel @willianjusten @dnbard @peterkokot @NoahBuscher @nmec @wasabeef @cjwirth @davidtheclark @gillesfabio @sturobson @AllThingsSmitty @afonsopacifer @deanhume @brunopulis @sachin1092 @sotayamashita

**Comment by h4cc** [comment]
Combining all lists would need to combine formatting rules and maybe CI-jobs like my list has for checking content.
I cant see the value/benefit in this approach.

What could be quite handsome, would be some kind of an aggregator, combining awesome lists automatically.

**Comment by dypsilon** [comment]
@sindresorhus ++

**Comment by avelino** [comment]
Are you another one who had this idea, I believe that we all have received an invite from someone with the same proposal.

I see no need.
https://github.com/fleveque/awesome-awesomes

**Comment by jondot** [comment]
I see no need as well, different people have a different sense of what's awesome, and making the one-true-list for what's awesome is bound for trouble.

**Comment by isRuslan** [comment]
These compilations will provide visibility for all lists:
- <a href="https://github.com/sindresorhus/awesome" target="_blank">sindresorhus/awesome</a> 
- <a href="https://github.com/bayandin/awesome-awesomeness" target="_blank">bayandin/awesome-awesomeness</a>

**Comment by n1trux** [comment]
The whole awesome-awesomes, awesome-awesomeness and whatnot lists should be merged into @sindresorhus' "awesome" repository as "master point" for discovery. In my opinion he's way more active and the list is structured better than the other "lists of lists".

I already merged and deleted mine.
Every topic should have its own list and maintainer.

@h4cc agreeing in that aggregator point. We need an easy to use web site for this. I propose http://getgrav.org as cms, as it could display markdown content without converting.

What do y'all think of that?

**Comment by joubertredrat** [comment]
Hi guys,

My idea isn't join or merge lists, is only create a common place for lists, like apache foundation as example, have a lot of open source projects, but each project has its own team.

but I agree with the @sindresorhus about ownership of list.

**Comment by avelino** [comment]
@joubertredrat history:
https://github.com/avelino/awesome-go/issues/112
https://github.com/avelino/awesome-go/issues/335

**Comment by bolshchikov** [comment]
The only value I see is such org can increase discoverability of different lists. @sindresorhus, not all lists in Github start w/ `awesome`, and some people might not even know that such lists exist. So if we put them under the organization, people might discover more.

**Comment by sindresorhus** [comment]
Not all lists in my`awesome` list do either. You're just repeating what has already been answered.

**Comment by aleksandar-todorovic** [comment]
1. There's a very little original content posted in our list. We just link to other resources.
2. The lists are very de-centralized and there will always be someone who will disagrees with the idea.
3. What about licensing? We're all using vastly different licenses for our list.
4. How to choose which one to include? There's like 4-5 of them for many topics.

In my opinion @sindresorhus's list does a great job combining them and it's the most popular one at the moment. Consider it as a search engine. It even got to GitHub's daily digest a couple of times. That's how I found out about it. Now I do respect other `awesome-awesomeness` lists as well, but I think his list does the best job at the moment, keeping the standards high.

Now the only thing we could theoretically do is to create a _real_ search engine (website) where people could type something (like `sysadmin`, `linux`or something) and be redirected to the appropriate list on GitHub.

Or we could cooperate with a search engine like @DuckDuckGo and create a new instant answer on their search engine that triggers the word `awesome`, searches through @sindresorhus's list and shows the list if it if finds one on his list as an instant answer. I went ahead and created an [Instant Answer idea](https://duck.co/ideas/idea/5991/instant-answering-github-s-awesome-lists-when-the) on the DuckDuckGo's site for suggesting instant answers. You could vote for it so it gets more attention (**WARNING**: Registration required to vote).

**Comment by n1trux** [comment]
@aleksandar-todorovic :+1: :+1:

maybe voting tomorrow, but certainly considering creating a simple site in August, when I have more free time.

**Comment by sindresorhus** [comment]
I already have an issue about creating some guidelines awesome lists are suggested to follow to keep up the quality. Feedback welcome: https://github.com/sindresorhus/awesome/issues/207

**Comment by diegocard** [comment]
I don´t see the need for a new organization. On the other hand, a set of guidelines could be useful.

**Comment by Fr0sT-Brutal** [comment]
So we had awesome lists, then awesome lists of awesome lists and now we need to go deeper? I don' think these lists differ much so it's easier to take the most full one as a base and merge links from other lists into it.

**Comment by n1trux** [comment]
closed because of @sindresorhus' https://github.com/sindresorhus/awesome/issues/207

Consensus is that we don't need an org but better quality, continue discussion there.
