### ISSUE TITLE
Nice to see an active fork for this list

### ISSUE THREAD

**Issue by unixorn** [n1trux/awesome-sysadmin#89]
If you want a collaborator to help manage pull requests, I'm willing to help out.

I currently maintain [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) and am one of the maintainers for [dotfiles.github.com](https://github.com/dotfiles/dotfiles.github.com), so I know what I'm getting into.

**Comment by n1trux** [comment]
Do some pull requests, install some software on this list and see if they're "certified awesome" :)
