### ISSUE TITLE
Project Copy

### ISSUE THREAD

**Issue by Kickball** [n1trux/awesome-sysadmin#92]
I've stumbled upon [https://n0where.net/open-source-sysadmin-resources/](https://n0where.net/open-source-sysadmin-resources/) which seems to be quite similar to this repository.

I thought you might like to know about it.

**Comment by n1trux** [comment]
well, they used a really old version of this list which was when @kahun had the "master list".

We should notify them to include the rest of the list and encourage them to link back to us :)

Do you want to do it or should I?

**Comment by Kickball** [comment]
If you want to do it seeing as your the project owner then that would be great.

Maybe ask them to credit you (or @kahun) with the list given that you/him did make it.

**Comment by n1trux** [comment]
I created an account and will tell them I'd like an updated version on their site and a link back to us :)

Thanks!

**Comment by Kickball** [comment]
No worries, glad to help!

**Comment by n1trux** [comment]
contacted them in their IRC channel. I'll leave this open until I get a response.

**Comment by n1trux** [comment]
didn't get any response, neither in IRC nor via eMail. I created a post in their forum:

https://n0where.net/forums/topic/please-give-credit-to-original-authors/

**Comment by n1trux** [comment]
they credit the appropriate creators now and I'm in contact with them.
